### ISSUE TITLE
Unable to connect to TinyTile board from Linux laptop

### ISSUE THREAD

**Issue by ljfranklin** [hybridgroup/gobot-workshop-2016#21]
I was unable to connect to the TinyTile board from my Ubuntu 16.04 laptop during the workshop, the error message was "unable to connect. Perhaps you need to flash your Arduino with Firmata?" After some additional forum digging, the fix was to add some additional `udev` rules. Threw in a docs PR here: https://github.com/hybridgroup/gobot/pull/437.

Thanks again for running the workshop!

**Comment by deadprogram** [comment]
Thanks @ljfranklin I merged the Gobot PR that you submitted. Now closing this issue, thanks again!
